#!/usr/bin/env bash
#This script configures a new Ubuntu machine for installing nginx

apt-get update
apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

service nginx restart
