#!/usr/bin/env bash
#This script configures and nginx server so that a redirect_me
#redirects to another page with code 301

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/jossvega103 permanent;" /etc/nginx/sites-enabled/default

service nginx restart
