#!/usr/bin/env bash
# This script installs and configures HAproxy on my lb-01 server

apt-get install -y software-properties-common
apt update
apt install haproxy

cp -a /etc/haproxy/haproxy.cfg{,.orig}

printf %s "
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

frontend my_frontend
    bind *:80
    mode http
    default_backend my_backend

backend my_backend
    mode http
    balance roundrobin
    option httpclose
    option forwardfor    
    server 42607-web-01 3.85.33.93:80 check
    server 42607-web-02 54.174.8.31:80 check" > /etc/haproxy/haproxy.cfg

service haproxy start
